{
 "title": "JWT Pizza Service",
 "description": "Let's go JWT Pizza!\n",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "HTTP Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"jwt-pizza-service\"} | json | type = `http`"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    { "expr": "active_users_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Factory Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"jwt-pizza-service\"} | json | type = `factory`"
    }
   ]
  },
  {
   "title": "Bitcoin",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "revenue_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SQL Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"jwt-pizza-service\"} | json | type = `query`"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(HTTPrequests_total{method=\"DELETE\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(HTTPrequests_total{method=\"GET\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(HTTPrequests_total{method=\"POST\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(HTTPrequests_total{method=\"PUT\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(HTTPrequests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "targets": [
    { "expr": "latency_milliseconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pizza Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "targets": [
    {
     "expr": "pizza_latency_milliseconds_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentication Success/Failures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 40 },
   "targets": [
    { "expr": "rate(auth_success_total[1m])", "legendFormat": "__auto" },
    { "expr": "rate(auth_fail_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pizzas sold and failed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 40 },
   "targets": [
    { "expr": "rate(sold_pizzas_total[1m])", "legendFormat": "__auto" },
    { "expr": "rate(failed_pizzas_total[24h])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Order Router",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "rate(requests_total{endpoint=\"getMenu\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(requests_total{endpoint=\"getOrders\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(requests_total{endpoint=\"addMenuItem\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(requests_total{endpoint=\"createOrder\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU & Memory",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 9, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_percent", "legendFormat": "__auto" },
    { "expr": "memory_percent", "legendFormat": "__auto" }
   ]
  }
 ]
}